version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: database
      MYSQL_USER: usuario_mysql
      MYSQL_PASSWORD: senha_mysql
    networks:
      - my_network
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    networks:
      - my_network
    depends_on:
      - db

networks:
  my_network:

volumes:
  mysql: